### ISSUE TITLE
Fix nav bar links in light mode

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#33]
Contents of the nav bar don't appear in light mode:
![image](https://github.com/jonbiemond/BCIT-Flex/assets/101326085/69cb8845-7295-4950-a57a-a5dacb9c8647)

**Comment by yr1404** [comment]
I would like to work on this one. Can you assign it to me?

**Comment by jonbiemond** [comment]
@yr1404 You're assigned, thanks for the contribution!
