### ISSUE TITLE
Make tables easier to read

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#34]
Without gridlines tables are hard to read. Add gridlines to the courses table and offering table.
Alternatively extra padding could help for a cleaner look than gridlines.
![image](https://github.com/jonbiemond/BCIT-Flex/assets/101326085/632ed8f7-d500-4dfa-a36e-eae511e718ac)

**Comment by yr1404** [comment]
Can you assign this to me?

**Comment by yr1404** [comment]
I have added alternate colours and padding to ease the reading of courses. Also, on hover on a particular course, the whole row changes to a darker colour. 
![Screenshot from 2023-09-17 16-40-03](https://github.com/jonbiemond/BCIT-Flex/assets/106465753/b8953d9a-23ab-4958-9859-c7b6ef7ea846)

**Comment by jonbiemond** [comment]
That's fantastic! While you're making changes I think we can drop the URL column and hyperlink the whole row if possible, or the Name if not.

**Comment by yr1404** [comment]
Added hyperlinks to the Name and removed the URL column
![Screenshot from 2023-09-21 20-03-39](https://github.com/jonbiemond/BCIT-Flex/assets/106465753/83916186-95fb-4dd5-9edf-d1856b6c8968)

**Comment by jonbiemond** [comment]
@yr1404 that looks fantastic! Can you please open a new PR when you're ready?
