### ISSUE TITLE
Paginate Courses view

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#36]
Limit courses displayed to 25 per page.

https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/pagination/

**Comment by MikeVarchola** [comment]
Hello, @jonbiemond  is this issue free to work on ? Could you assign it to me ?  Thanks.

**Comment by jonbiemond** [comment]
Hi @MikeVarchola, of course, you're assigned!

**Comment by MikeVarchola** [comment]
@jonbiemond  I have my setup of project working, created branch and prob this week I will get some work done on this.

**Comment by jonbiemond** [comment]
@MikeVarchola Fantastic, let me know if you have any questions. I am also adding a Programs page soon, which could also benefit from this.

**Comment by MikeVarchola** [comment]
@jonbiemond Hello, I cant push into my branch that I created.

`remote: Permission to jonbiemond/BCIT-Flex.git denied to MikeVarchola.
fatal: unable to access 'https://github.com/jonbiemond/BCIT-Flex.git/': The requested URL returned error: 403
Pushing to https://github.com/jonbiemond/BCIT-Flex.git
`

Do you need to give me some kind of access ?

**Comment by jonbiemond** [comment]
Hey @MikeVarchola , looking forward to seeing your changes! Are you working in a forked copy of the repo? If not you'll need to do that to open a PR. Here are some steps you may follow:

* See details on how to create a fork here: https://docs.github.com/en/get-started/quickstart/fork-a-repo
* And since you've already made the changes in a clone of this repo, here's how you can make the new fork the remote for your local version: https://docs.github.com/en/get-started/quickstart/fork-a-repo
