### ISSUE TITLE
Missing price in offering info

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#54]
The price field is `0` and doesn't match the BCIT site. This appears to be due to a change on the BCIT site resulting in a parsing error. 
https://www.bcitflex.tech/courses/8

**Comment by VleraBllacaa** [comment]
Hey there, I want to contribute in this reported bug!

**Comment by jonbiemond** [comment]
Hi @VleraBllacaa, please do! Thanks for your help, it's really appreciated!
