### ISSUE TITLE
Add search feature

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#61]
Add the ability to search by course name.

**Comment by Dominik26-1** [comment]
I would like to contribute to this issue especially for backend part.

**Comment by jonbiemond** [comment]
@Dominik26-1 I've assigned you! Feel free to focus on just the backend for now. I'll add more details soon.

**Comment by Dominik26-1** [comment]
I think, its so far so clear. I've already started on it. Can you please give me permission to push to my created development branch.

remote: Permission to jonbiemond/BCIT-Flex.git denied to Dominik26-1.
fatal: unable to access 'https://github.com/jonbiemond/BCIT-Flex.git/'

**Comment by jonbiemond** [comment]
Hi @Dominik26-1 , instead of pushing changes directly to this repo could you please create a fork and make the changes there?

See details on how to create a fork here: https://docs.github.com/en/get-started/quickstart/fork-a-repo
And since you've already made the changes in a clone of this repo, here's how you can make the new fork the remote for your local version: https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by jonbiemond** [comment]
Hey @Dominik26-1, I look forward to seeing your PR! Is there anything I can help with?

**Comment by Dominik26-1** [comment]
Hi, I have locally prepared PR but I noticed you changed main code so need to update my changes with yours.

**Comment by jonbiemond** [comment]
Hey @Dominik26-1, don't worry about that for now. Let's leave it as the very last step before merging. I can also help resolve any conflicts.

**Comment by Dominik26-1** [comment]
I created PR some minutes ago, so you can have a look (add some functionality for not exact matching, make sense for me to not only return records with the same word)
