### ISSUE TITLE
Add program selection interface to course index

### ISSUE THREAD

**Issue by jonbiemond** [jonbiemond/BCIT-Flex#64]
Allow user to filter courses by picking a program.

**Comment by jonbiemond** [comment]
@0x53616D75656C Which programs do you think I should add to the list of programs that courses can be filtered by? If I do every single program including a COMP course for example, I get 26. I'd rather not have that many. Maybe I can just expose some with check boxes, and the the rest in a drop down.
```
+-------------------------+-------+
| credential              | count |
|-------------------------+-------|
| Associate Certificate   | 14    |
| Bachelor of Science     | 5     |
| Certificate             | 2     |
| Diploma                 | 1     |
| Microcredential         | 3     |
| Statement of Completion | 1     |
+-------------------------+-------+
```

**Comment by 0x53616D75656C** [comment]
Two ways that come to mind

1. List all programs by credential
![List all programs drawio](https://github.com/jonbiemond/BCIT-Flex/assets/109733822/97563094-505a-49cc-8266-609f3cca91f0)
2. List related programs in each course under offerings

**Comment by jonbiemond** [comment]
@0x53616D75656C Thanks for the detailed response! I like the first way. I've roughly implemented that via the programs page: https://bcitflex.tech/programs

I'm still looking to implement the ability to view a program's courses and apply course filters. I don't know if that belongs within a Program's page itself, or if there should be a way to navigate to the course index page from a program page that shows only the program's courses. 

I also have an idea where a user could save a program to their account and then by default it only shows them their program's courses.
